apiVersion: apps/v1
kind: Deployment
metadata:
  name: reviews
spec:
  replicas: 2
  selector:
    matchLabels:
      app: reviews
  template:
    metadata:
      labels:
        app: reviews
    spec:
      containers:
        - name: reviews
          image: istio/examples-bookinfo-reviews-v2
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 9080
          env:
            - name: RATINGS_HOSTNAME
              value: ratings
